name: PR Auto Assign Test

on:
  pull_request:

jobs:
  reviewer:
    if: github.base_ref!= 'develop' # ignore the pull request merging into develop branch.
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: echo
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "$GITHUB_TOKEN"
      - uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["test"]
            });
