name: PR Auto Assign

on:
  pull_request:
    types: [opened, edited]

jobs:
  reviewer:
    if: github.base_ref!= 'develop' && github.event.pull_request.draft == false # ignore the pull request merging into develop branch.
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: echo
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo github.event.pull_request.draft
      - uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              team_reviewers: ['test']
            })
